matrix:
        include:
                - dist: xenial
                  language: python
                  python:
                            - 3.5
                  install:
                            - pip install 'pytest>=4.4.0' --upgrade
                            - pip install .
                  branches:
                          only:
                            - master
                            - devel
                  script:
                            - pytest
                
                - dist: xenial
                  language: python
                  python:
                            - 3.6
                            - 3.7
                  install:
                            - pip install 'pytest>=4.4.0' --upgrade
                            - pip install .
                            - pip install mkdocs pymdown-extensions nbconvert mknotebooks mkdocs-material
                  branches:
                          only:
                            - master
                            - devel
                  script:
                            - pytest
                            - mkdocs build
